# Generated by Django 3.1.1 on 2020-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding_name', models.CharField(choices=[('KIE', "Kielh's"), ('INN', 'Innisfree'), ('BIO', 'Biore'), ('BUR', 'Burberry'), ('CET', 'Cetaphil'), ('CER', 'Cerave'), ('CLI', 'Clinique'), ('COO', 'Cocoon'), ('DHC', 'DHC'), ('EST', 'Estee Lauder'), ('ACN', 'Acnes'), ('HAD', 'Hada Labo'), ('HUX', 'Huxley'), ('LAR', 'La roche Posay'), ('LAN', 'Lancome'), ('LOR', 'Loreal'), ('MIS', 'Missha'), ('MUR', 'Murad'), ('NEU', 'Neutrogena'), ('OMI', 'Omi'), ('OHU', 'Ohui'), ('PAU', "Paula's Choice"), ('SEN', 'Senka'), ('SIM', 'Simple'), ('SOM', 'Sum by Mi'), ('SUL', 'Sulwhasoo'), ('THA', "Thayer's"), ('VAS', 'Vaseline'), ('SK2', 'SKII'), ('LAM', 'La Mer'), ('ELE', 'Drunk Elephant'), ('FRE', 'Fresh'), ('TAT', 'Tatcha'), ('ORD', 'The Ordinary'), ('GLO', 'Glossier')], max_length=3)),
                ('brandDescript', models.TextField()),
            ],
        ),
    ]
