# Generated by Django 3.1.1 on 2020-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('news_img', models.ImageField(upload_to='news/images/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('summary', models.TextField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
