# Generated by Django 3.1.1 on 2020-11-13 09:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2020, 11, 13, 16, 12, 2, 974243)),
            preserve_default=False,
        ),
    ]
