# Generated by Django 3.1.1 on 2020-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='news/static/news/images/'),
        ),
    ]
