# Generated by Django 3.1.1 on 2020-11-14 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 14, 22, 14, 20, 745029)),
        ),
    ]
