# Generated by Django 3.1.1 on 2020-11-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201115_0150'),
        ('news', '0004_auto_20201115_0839'),
    ]

    operations = [
    ]
