# Generated by Django 3.1.3 on 2020-11-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_merge_20201118_1350'),
        ('news', '0007_auto_20201117_1526'),
    ]

    operations = [
    ]
