# Generated by Django 3.1.3 on 2020-11-19 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20201119_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='news/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
