# Generated by Django 3.1.1 on 2020-11-13 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('skintype', models.CharField(choices=[('DRY', 'Dry Skin'), ('OIL', 'Oliy Skin'), ('COMBI', 'Combination Skin')], max_length=5)),
                ('skin_cond', models.CharField(choices=[('SEN', 'Sensitive Skin'), ('ACNE', 'Acne Skin'), ('AGE', 'Aging Skin')], max_length=5)),
                ('vote_down', models.IntegerField(default=0)),
                ('vote_up', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('MAKEUP_RM', 'Makeup Remover'), ('CLEANSE', 'Cleanser'), ('TONER', 'Toner'), ('SERUM', 'Serum'), ('MOIST', 'Moisturizer'), ('LOTION', 'Lotion'), ('MASK', 'Mask'), ('EYE', 'Eye Care'), ('SUN', 'Sun Care'), ('EXFOL', 'Exfoliators'), ('LIP', 'Lip Treatment')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 11, 13, 16, 3, 37, 969604))),
                ('vote_down', models.IntegerField(default=0)),
                ('vote_up', models.IntegerField(default=0)),
                ('owner_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
