# Generated by Django 3.1.3 on 2020-11-14 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201113_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 1, 50, 17, 514365)),
        ),
    ]
