# Generated by Django 3.1.1 on 2020-11-15 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201114_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 8, 39, 47, 963286)),
        ),
    ]
