# Generated by Django 3.1.1 on 2020-12-10 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201210_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 16, 24, 19, 262196)),
        ),
    ]
