# Generated by Django 3.1.3 on 2020-11-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201115_0150'),
        ('product', '0004_auto_20201115_0839'),
    ]

    operations = [
    ]
