# Generated by Django 3.1.1 on 2020-11-17 08:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_merge_20201117_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_size_in_ml',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 15, 24, 45, 772862)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MAKEUP_RM', 'Makeup Remover'), ('CLEANSE', 'Cleanser'), ('TONER', 'Toner'), ('SERUM', 'Serum'), ('MOIST', 'Moisturizer'), ('LOTION', 'Lotion'), ('MASK', 'Mask'), ('EYE', 'Eye Care'), ('SUN', 'Sun Care'), ('EXFOL', 'Exfoliators'), ('LIP', 'Lip Treatment')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_cond',
            field=models.CharField(choices=[('SEN', 'Sensitive Skin'), ('ACNE', 'Acne Skin'), ('AGE', 'Aging Skin')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='skintype',
            field=models.CharField(choices=[('DRY', 'Dry Skin'), ('OIL', 'Oliy Skin'), ('COMBI', 'Combination Skin'), ('NORM', 'Normal Skin'), ('ALL', 'All Skin Type')], max_length=5, null=True),
        ),
    ]
