# Generated by Django 3.1.1 on 2020-12-11 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201211_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 12, 45, 37, 569279)),
        ),
    ]
