# Generated by Django 3.1.1 on 2020-11-17 08:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201117_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 15, 26, 14, 674017)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MAKEUP_RM', 'Makeup Remover'), ('CLEANSE', 'Cleanser'), ('TONER', 'Toner'), ('SERUM', 'Serum'), ('MOIST', 'Moisturizer'), ('LOTION', 'Lotion'), ('MASK', 'Mask'), ('EYE', 'Eye Care'), ('SUN', 'Sun Care'), ('EXFOL', 'Exfoliators'), ('LIP', 'Lip Treatment')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='skintype',
            field=models.CharField(choices=[('DRY', 'Dry Skin'), ('OIL', 'Oliy Skin'), ('COMBI', 'Combination Skin'), ('NORM', 'Normal Skin'), ('ALL', 'All Skin Type')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
