# Generated by Django 3.1.3 on 2020-11-19 03:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_merge_20201119_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branding_name',
            field=models.CharField(choices=[('KIE', "Kielh's"), ('INN', 'Innisfree'), ('BIO', 'Biore'), ('BUR', 'Burberry'), ('CET', 'Cetaphil'), ('CER', 'Cerave'), ('CLI', 'Clinique'), ('COO', 'Cocoon'), ('DHC', 'DHC'), ('EST', 'Estee Lauder'), ('ACN', 'Acnes'), ('HAD', 'Hada Labo'), ('HUX', 'Huxley'), ('LAR', 'La roche Posay'), ('LAN', 'Lancome'), ('LOR', 'Loreal'), ('MIS', 'Missha'), ('MUR', 'Murad'), ('NEU', 'Neutrogena'), ('OMI', 'OMI'), ('OHU', 'Ohui'), ('PAU', "Paula's Choice"), ('SEN', 'Senka'), ('SIM', 'Simple'), ('SOM', 'Sum by Mi'), ('SUL', 'Sulwhasoo'), ('THA', 'Thayes'), ('VAS', 'Vaseline'), ('SK2', 'SKII'), ('LAM', 'La Mer'), ('ELE', 'Drunk Elephant'), ('FRE', 'Fresh'), ('TAT', 'Tatcha'), ('ORD', 'The Ordinary'), ('GLO', 'Glossier')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 22, 12, 609746)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
